# Generated by Django 5.1.2 on 2024-11-17 19:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TMDB", "0007_alter_movie_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieSubtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subtitle_file",
                    models.FileField(
                        help_text="Stored subtitle file",
                        max_length=500,
                        storage="django.core.files.storage.storages.subtitles",
                        upload_to="subtitles/%Y/%m/%d/",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        help_text="Source of subtitle (e.g. 'opensubtitles', 'manual')",
                        max_length=100,
                    ),
                ),
                (
                    "subtitle_format",
                    models.CharField(
                        choices=[
                            ("srt", "SubRip"),
                            ("vtt", "WebVTT"),
                            ("ass", "Advanced SubStation Alpha"),
                            ("ssa", "SubStation Alpha"),
                        ],
                        help_text="Subtitle file format",
                        max_length=3,
                    ),
                ),
                ("version", models.CharField(max_length=50)),
                ("language", models.CharField(max_length=10)),
                ("content_hash", models.CharField(max_length=64)),
                (
                    "quality_score",
                    models.FloatField(
                        help_text="Calculated quality score (0-1)", null=True
                    ),
                ),
                ("metadata", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_processed",
                    models.BooleanField(
                        default=False, help_text="subtitle text processed "
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtitles",
                        to="TMDB.movie",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["movie", "language", "is_active"],
                        name="subtitles_m_movie_i_15603a_idx",
                    ),
                    models.Index(
                        fields=["movie", "version"],
                        name="subtitles_m_movie_i_12b69f_idx",
                    ),
                    models.Index(
                        fields=["content_hash"], name="subtitles_m_content_c00bf6_idx"
                    ),
                    models.Index(
                        fields=["quality_score"], name="subtitles_m_quality_e2138d_idx"
                    ),
                    models.Index(
                        fields=["is_processed"], name="subtitles_m_is_proc_b59318_idx"
                    ),
                ],
                "unique_together": {("movie", "language", "content_hash")},
            },
        ),
    ]
