# Generated by Django 5.1.2 on 2024-11-20 03:09

import subtitles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0007_alter_movie_created_at_and_more"),
        ("subtitles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesubtitle",
            name="subtitle_file",
            field=models.FileField(
                help_text="Stored subtitle file",
                max_length=500,
                storage=subtitles.models.SubtitleS3Storage(),
                upload_to="",
            ),
        ),
        migrations.AlterField(
            model_name="moviesubtitle",
            name="version",
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name="moviesubtitle",
            index=models.Index(
                fields=["language", "is_processed", "is_active"],
                name="subtitles_m_languag_949f78_idx",
            ),
        ),
    ]
