# Generated by Django 5.1.2 on 2024-11-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0007_alter_movie_created_at_and_more"),
        ("subtitles", "0002_alter_moviesubtitle_subtitle_file_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="moviesubtitle",
            name="subtitles_m_is_proc_b59318_idx",
        ),
        migrations.RemoveIndex(
            model_name="moviesubtitle",
            name="subtitles_m_languag_949f78_idx",
        ),
        migrations.RemoveField(
            model_name="moviesubtitle",
            name="is_processed",
        ),
        migrations.AddField(
            model_name="moviesubtitle",
            name="last_processing_attempt",
            field=models.DateTimeField(
                blank=True, help_text="Timestamp of last processing attempt", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviesubtitle",
            name="processed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when processing completed successfully",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="moviesubtitle",
            name="processing_attempts",
            field=models.IntegerField(
                default=0, help_text="Number of processing attempts"
            ),
        ),
        migrations.AddField(
            model_name="moviesubtitle",
            name="processing_error",
            field=models.TextField(
                blank=True, help_text="Error message if processing failed", null=True
            ),
        ),
        migrations.AddField(
            model_name="moviesubtitle",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("processed", "Processed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Current processing status of the subtitle",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="moviesubtitle",
            index=models.Index(
                fields=["processing_status"], name="subtitles_m_process_8207f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moviesubtitle",
            index=models.Index(
                fields=["language", "processing_status", "is_active"],
                name="subtitles_m_languag_cad6d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="moviesubtitle",
            index=models.Index(
                fields=["last_processing_attempt"],
                name="subtitles_m_last_pr_070389_idx",
            ),
        ),
    ]
