# Generated by Django 5.1.2 on 2024-11-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subtitles",
            "0003_remove_moviesubtitle_subtitles_m_is_proc_b59318_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moviesubtitle",
            name="subtitle_is_processed",
            field=models.BooleanField(
                default=False, help_text="subtitle text as processed"
            ),
        ),
    ]
