# Generated by Django 5.1.2 on 2024-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subtitles", "0004_moviesubtitle_subtitle_is_processed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moviesubtitle",
            name="subtitle_is_processed",
            field=models.BooleanField(
                default=False, help_text="Subtitle text as processed"
            ),
        ),
    ]
