[pytest]
DJANGO_SETTINGS_MODULE = media_index.settings
python_files = tests.py test_*.py *_tests.py
addopts = -p no:warnings --strict-markers --no-migrations --reuse-db
markers =
    asyncio: mark test as asyncio

[coverage:run]
source = .
omit =
    *apps.py,
    *settings.py,
    *urls.py,
    *wsgi.py,
    *asgi.py,
    manage.py,
    conftest.py,
    *base.py,
    *development.py,
    *production.py,
    *__init__.py,
    */migrations/*,
    *tests/*,
    tests/*,
    */env/*,
    */venv/*,

[coverage:report]
show_missing = True

