# Generated by Django 5.1.2 on 2024-11-08 22:15

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("TMDB", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAnalysisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version of analysis function/algorithm used",
                        max_length=50,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("book", "Book"),
                            ("song", "Song"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subtitle_id", models.IntegerField()),
                (
                    "subtitle_version",
                    models.CharField(
                        help_text="Track which subtitle version was analyzed",
                        max_length=50,
                    ),
                ),
                (
                    "lexical_analysis",
                    models.JSONField(
                        help_text="JSON containing tokens, lexemes, POS, and language distribution data"
                    ),
                ),
                ("is_latest", models.BooleanField()),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_analysis_results",
                        to="TMDB.movie",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["movie", "version"],
                        name="language_an_movie_i_b9ae63_idx",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["lexical_analysis"],
                        name="language_an_lexical_4d9a46_gin",
                    ),
                ],
            },
        ),
    ]
