# Generated by Django 5.1.2 on 2024-11-14 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_analysis", "0002_mediaanalysisresult_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaanalysisresult",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
