# Generated by Django 5.1.2 on 2024-11-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_analysis", "0003_alter_mediaanalysisresult_created_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaanalysisresult",
            name="type",
        ),
        migrations.AddField(
            model_name="mediaanalysisresult",
            name="kind",
            field=models.CharField(
                choices=[("movie", "Movie"), ("book", "Book"), ("song", "Song")],
                default="movie",
                help_text="Media type",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
