# Generated by Django 5.1.2 on 2024-11-21 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_analysis", "0004_remove_mediaanalysisresult_type_and_more"),
        ("subtitles", "0002_alter_moviesubtitle_subtitle_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediaanalysisresult",
            name="subtitle_id",
        ),
        migrations.AddField(
            model_name="mediaanalysisresult",
            name="subtitle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="media_analysis_results",
                to="subtitles.moviesubtitle",
            ),
        ),
        migrations.AlterField(
            model_name="mediaanalysisresult",
            name="lexical_analysis",
            field=models.JSONField(
                help_text="JSON containing concepts, pos_stats, sentences_count, sentences_avg_length, and difficulty"
            ),
        ),
    ]
