# Generated by Django 5.1.2 on 2024-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language_analysis", "0005_remove_mediaanalysisresult_subtitle_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaanalysisresult",
            name="kind",
            field=models.CharField(
                choices=[("movie", "Movie"), ("book", "Book"), ("song", "SONG")],
                help_text="Media type",
                max_length=10,
            ),
        ),
    ]
