# Generated by Django 5.1.2 on 2024-11-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("latest_analysis_id", models.IntegerField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("original_title", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=10)),
                ("original_language", models.CharField(max_length=10)),
                ("year", models.IntegerField()),
                ("release_date", models.DateField()),
                ("runtime", models.IntegerField(null=True)),
                ("overview", models.TextField()),
                ("poster_url", models.URLField(max_length=500, null=True)),
                ("backdrop_url", models.URLField(max_length=500, null=True)),
                ("vote_average", models.DecimalField(decimal_places=1, max_digits=3)),
                ("vote_count", models.IntegerField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tmdb_id"], name="TMDB_movie_tmdb_id_3cc60d_idx"
                    ),
                    models.Index(fields=["title"], name="TMDB_movie_title_db16a7_idx"),
                    models.Index(fields=["year"], name="TMDB_movie_year_7e7745_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="TMDBSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.IntegerField(help_text="Year being synced")),
                (
                    "language",
                    models.CharField(
                        help_text="Language code (e.g., en-US)", max_length=10
                    ),
                ),
                ("job_id", models.CharField(help_text="RQ job ID", max_length=100)),
                ("priority", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("attempts", models.IntegerField(default=0)),
                ("last_attempt", models.DateTimeField(null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("movies_processed", models.IntegerField(default=0)),
                ("movies_failed", models.IntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["status", "priority"],
                        name="TMDB_tmdbsy_status_ad9722_idx",
                    ),
                    models.Index(
                        fields=["year", "language"], name="TMDB_tmdbsy_year_64d609_idx"
                    ),
                ],
            },
        ),
    ]
