# Generated by Django 5.1.2 on 2024-11-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="latest_analysis_id",
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
