# Generated by Django 5.1.2 on 2024-11-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0002_alter_movie_latest_analysis_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="year",
            field=models.IntegerField(null=True),
        ),
    ]
