# Generated by Django 5.1.2 on 2024-11-08 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0003_alter_movie_year"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="TMDB_movie_year_7e7745_idx",
        ),
        migrations.RemoveField(
            model_name="movie",
            name="year",
        ),
    ]
