# Generated by Django 5.1.2 on 2024-11-09 19:27

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0004_remove_movie_tmdb_movie_year_7e7745_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
