# Generated by Django 5.1.2 on 2024-11-14 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0005_movie_genres"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="movie",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tmdbsyncqueue",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name="tmdbsyncqueue",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="tmdbsyncqueue",
            name="language",
            field=models.CharField(help_text="Language code (e.g., en)", max_length=10),
        ),
    ]
