# Generated by Django 5.1.2 on 2024-11-14 21:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0006_movie_created_at_movie_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="tmdbsyncqueue",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
