# Generated by Django 5.1.2 on 2024-12-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0007_alter_movie_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="difficulty",
            field=models.FloatField(default=0.0),
        ),
    ]
