# Generated by Django 5.1.2 on 2024-12-05 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0008_movie_difficulty"),
        ("TMDB", "008_enable_trigram_extensions"),
    ]

    operations = []
