# Generated by Django 5.1.2 on 2024-12-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0009_merge_20241205_2341"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="TMDB_movie_title_db16a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_title_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_orig_title_trgm_idx",
        ),
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_vote_count_idx",
        ),
        migrations.AddField(
            model_name="movie",
            name="author",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="movie",
            name="difficulty",
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
