# Generated by Django 5.1.2 on 2024-12-09 18:33

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0011_add_search_vector_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="title_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
    ]
