# Generated by Django 5.1.2 on 2024-12-10 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("TMDB", "0012_alter_movie_title_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="author",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
